services:
  db:
    image: mysql:8.0
    container_name: MySQL_DB
    environment:
      MYSQL_DATABASE: LaravelDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: Redis_DB
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  app:
    image: sasit48/laravel-fibonacci-calculator
    container_name: Laravel_APP
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: >
      sh -c "php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"

  worker:
    image: sasit48/laravel-fibonacci-calculator
    container_name: Laravel_Worker
    depends_on:
      - db
      - redis
    command: php artisan queue:work --daemon

  frontend:
    image: sasit48/react-fibonacci
    container_name: React_Frontend
    ports:
      - "5174:80"

volumes:
  db-data:
  redis-data:
